# Generated by Django 5.1.1 on 2024-10-11 17:45

import cloudinary.models
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscript',
            name='answer',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=core.models.answer_upload_path),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=core.models.question_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hwfiles',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=core.models.user_directory_path),
        ),
    ]
