# Generated by Django 5.1.1 on 2024-10-12 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tempprofile_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
